# Generated by Django 4.1.3 on 2023-01-24 12:44

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('on_site_option', models.BooleanField(default=False, verbose_name='On-Site Option')),
                ('remote_option', models.BooleanField(default=False, verbose_name='Remote Option')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.vacancycategory', verbose_name='Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.location', verbose_name='Location')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
