# Generated by Django 4.1.7 on 2023-02-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('resume', models.FileField(upload_to='uploads/freelance_resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Freelance application',
                'verbose_name_plural': 'Freelance applications',
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('resume', models.FileField(upload_to='uploads/vacancy_resume', verbose_name='Resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy application',
                'verbose_name_plural': 'Vacancy applications',
            },
        ),
    ]
