# Generated by Django 4.1.7 on 2023-03-02 02:00

import careers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_freelanceapplication_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceapplication',
            name='resume',
            field=models.FileField(upload_to='uploads/freelance_resume', validators=[careers.validators.file_size], verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='resume',
            field=models.FileField(upload_to='uploads/vacancy_resume', validators=[careers.validators.file_size], verbose_name='Resume'),
        ),
    ]
