# Generated by Django 4.1.4 on 2023-01-13 12:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_location_vacancy_content_vacancy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='picture',
            field=models.ImageField(default=123, upload_to='', verbose_name='Picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
