# Generated by Django 4.1.4 on 2023-01-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vacancy_picture_alter_vacancy_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='VacancyCategory',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacancycategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
