# Generated by Django 4.1.7 on 2023-02-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
