# Generated by Django 4.1.4 on 2022-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
