# Generated by Django 4.1.4 on 2022-12-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
