# Generated by Django 4.1.4 on 2022-12-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_author_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='blank_avatar.jpg', upload_to=''),
        ),
    ]
