# Generated by Django 4.1.4 on 2023-01-06 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.CharField(blank=True, max_length=255, verbose_name='Time to read'),
        ),
    ]
