# Generated by Django 4.1.3 on 2023-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(default=123, max_length=500),
            preserve_default=False,
        ),
    ]
