# Generated by Django 4.1.3 on 2023-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=500, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='blank_avatar.jpg', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='occupation',
            field=models.CharField(max_length=255, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tag'),
        ),
    ]
