# Generated by Django 4.1.4 on 2022-12-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0002_rename_name_work_heading_work_approach_work_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
