# Generated by Django 4.1.4 on 2022-12-21 07:57

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0003_alter_work_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AddField(
            model_name='work',
            name='color',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='work',
            name='approach',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Approach'),
        ),
        migrations.AlterField(
            model_name='work',
            name='brief',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Brief'),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='work',
            name='deliverables',
            field=ckeditor.fields.RichTextField(verbose_name='Deliverables'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='work',
            name='impact',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='work',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='work',
            name='interesting_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Interesting Features'),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='work',
            name='logo',
            field=models.FileField(upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='metric',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Metric'),
        ),
        migrations.AlterField(
            model_name='work',
            name='picture1',
            field=models.ImageField(upload_to='', verbose_name='Picture 1'),
        ),
        migrations.AlterField(
            model_name='work',
            name='picture2',
            field=models.ImageField(upload_to='', verbose_name='Picture 2'),
        ),
        migrations.AlterField(
            model_name='work',
            name='picture3',
            field=models.ImageField(upload_to='', verbose_name='Picture 3'),
        ),
        migrations.AlterField(
            model_name='work',
            name='team_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Team Size'),
        ),
        migrations.AlterField(
            model_name='work',
            name='what_we_built',
            field=ckeditor.fields.RichTextField(verbose_name='What We Built'),
        ),
        migrations.AlterField(
            model_name='work',
            name='what_we_did',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='What We Did'),
        ),
    ]
