# Generated by Django 4.1.4 on 2022-12-21 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0005_work_preview_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='logo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])], verbose_name='Logo'),
        ),
    ]
