# Generated by Django 4.1.4 on 2022-12-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0006_alter_work_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Team'),
        ),
    ]
