# Generated by Django 4.1.4 on 2022-12-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0007_work_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='success_story_picture',
            field=models.ImageField(default='img_bbc_lg@2x-1.png', upload_to=''),
        ),
    ]
