# Generated by Django 4.1.4 on 2022-12-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0008_work_success_story_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Picture 2'),
        ),
    ]
