# Generated by Django 4.1.4 on 2022-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0009_alter_work_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='brief',
            field=models.TextField(null=True, verbose_name='Brief'),
        ),
    ]
