# Generated by Django 4.1.4 on 2023-01-13 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0010_alter_work_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
    ]
