# Generated by Django 4.1.4 on 2023-01-13 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0011_work_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='logo',
        ),
        migrations.AddField(
            model_name='work',
            name='logo_dark',
            field=models.FileField(default='Black_question_mark.png', help_text='Please upload a logo that will be visible on light background', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])], verbose_name='Dark Logo'),
        ),
        migrations.AddField(
            model_name='work',
            name='logo_light',
            field=models.FileField(default='78-784866_png-white-question-mark.png', help_text='Please upload a logo that will be visible on dark background', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])], verbose_name='Light Logo'),
        ),
    ]
