# Generated by Django 4.1.4 on 2023-01-13 12:26

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0012_remove_work_logo_work_logo_dark_work_logo_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='color',
            field=colorfield.fields.ColorField(default='#000', help_text='Please select background color for this work that will be used in the Works page.', image_field=None, max_length=18, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='work',
            name='logo_dark',
            field=models.FileField(default='Black_question_mark.png', help_text='Please upload a logo that will be visible on light background.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Dark Logo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='logo_light',
            field=models.FileField(default='78-784866_png-white-question-mark.png', help_text='Please upload a logo that will be visible on dark background.', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Light Logo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='preview_picture',
            field=models.ImageField(blank=True, default='img_bbc_lg@2x-1.png', upload_to='', verbose_name='Preview Picture'),
        ),
        migrations.AlterField(
            model_name='work',
            name='success_story_picture',
            field=models.ImageField(default='img_bbc_lg@2x-1.png', upload_to='', verbose_name='Success Story Picture'),
        ),
    ]
