# Generated by Django 4.1.3 on 2023-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0013_alter_work_color_alter_work_logo_dark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='impact',
            field=models.TextField(blank=True, null=True, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='work',
            name='interesting_features',
            field=models.TextField(blank=True, null=True, verbose_name='Interesting Features'),
        ),
        migrations.AlterField(
            model_name='work',
            name='metric',
            field=models.TextField(blank=True, null=True, verbose_name='Metric'),
        ),
    ]
