# Generated by Django 4.1.3 on 2023-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0014_alter_work_impact_alter_work_interesting_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='approach',
            field=models.TextField(blank=True, null=True, verbose_name='Approach'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
