# Generated by Django 4.1.3 on 2023-01-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0015_alter_work_approach_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='what_we_built',
            field=models.TextField(verbose_name='What We Built'),
        ),
    ]
