# Generated by Django 4.1.7 on 2023-02-23 12:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_works', '0016_alter_work_what_we_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
