# Generated by Django 4.1.4 on 2023-01-02 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_bot', '0002_rename_chat_id_telegramuser_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
