# Generated by Django 4.1.4 on 2023-01-04 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_bot', '0003_alter_telegramuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
