# Generated by Django 4.1.4 on 2023-01-04 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_bot', '0004_alter_telegramuser_chat_alter_telegramuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat',
            field=models.IntegerField(verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='telegramuser',
            constraint=models.UniqueConstraint(fields=('user', 'chat'), name='unique_user_chat_combination'),
        ),
    ]
