# Generated by Django 4.1.3 on 2023-02-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_bot', '0006_telegramuser_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
    ]
