# Generated by Django 4.1.4 on 2023-01-02 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='logo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])], verbose_name='Logo'),
        ),
    ]
