# Generated by Django 4.1.3 on 2023-02-10 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_social_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFormRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Business email')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('business_title', models.CharField(max_length=255, verbose_name='Business title')),
                ('project_details', models.TextField(verbose_name='Project details')),
                ('budget', models.CharField(max_length=255, verbose_name='Budget')),
                ('needs', models.CharField(max_length=255, verbose_name='Needs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
