# Generated by Django 4.1.3 on 2023-02-10 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_mainformrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryFormRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Business email')),
                ('project_details', models.TextField(verbose_name='Project details')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
