# Generated by Django 4.1.7 on 2023-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_secondaryformrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainformrequest',
            options={'verbose_name': 'Main Form Request', 'verbose_name_plural': 'Main Form Requests'},
        ),
        migrations.AlterModelOptions(
            name='secondaryformrequest',
            options={'verbose_name': 'Secondary Form Request', 'verbose_name_plural': 'Secondary Form Requests'},
        ),
        migrations.AlterField(
            model_name='mainformrequest',
            name='needs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Needs'),
        ),
    ]
